### ISSUE TITLE
Scroll VN list

### ISSUE THREAD

**Issue by RobHones** [micah686/VnManager#11]
Please add a scrollbar to the VN/Categories list, once the list becomes to long the program becomes useless if you can't access/see the entry for the visual novel.

**Comment by micah686** [comment]
I am aware of this issue, and I am currently working on redoing the program in order to make the code cleaner, and work on fixing the GUI as well. I have attached a build where there still is a scrollbar on the vn list.

**Comment by micah686** [comment]
Closed due to redesign work on the v3 version
