### ISSUE TITLE
Crash when Importing data

### ISSUE THREAD

**Issue by suzuya26** [micah686/VnManager#29]
i just reinstall the app, then when i tried to import data, (browse , select file, then ok)  then a notification pop up appears  says "export data crashed", the app not responding.

sorry for my english.

**Comment by micah686** [comment]
Fixed in [1.0.5](https://github.com/micah686/VnManager/releases/tag/1.0.5). Let me know if it still crashes.

**Comment by micah686** [comment]
Closing due to lack of update. If there it still crashes, feel free to re-open the issue.
