### ISSUE TITLE
Sexual Lv and Password is not working

### ISSUE THREAD

**Issue by GhostM9** [micah686/VnManager#36]
i make the password but when i open is not ask for password is just open my vns list, for sexual lv, Sanoba Witch cover is not showing even though i set the setting to explicit.
![Screenshot (1989)](https://user-images.githubusercontent.com/80044144/109963592-fd772e00-7d1a-11eb-8966-ecc162389ba1.png)
![Screenshot (1990)](https://user-images.githubusercontent.com/80044144/109963613-0536d280-7d1b-11eb-96eb-7c6a911da8b4.png)

**Comment by foxy9000** [comment]
Same thing with the Sanoba Witch cover picture and with other two (SoniComi and Koi iro Chu! Lips)

**Comment by LordAxerion** [comment]
Same problem with the Raidy series.

**Comment by micah686** [comment]
Should be fixed in [1.0.5](https://github.com/micah686/VnManager/releases/tag/1.0.5). Let me know if the issue still persists.

**Comment by foxy9000** [comment]
The cover picture are fixed for me Thank you!

**Comment by GhostM9** [comment]
cover is work now thank
